[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/search"
  to = "/.netlify/functions/search"
  status = 200

[[redirects]]
  from = "/api/details"
  to = "/.netlify/functions/details"
  status = 200
